<a href="https://colab.research.google.com/github/digvijay-sharma123/Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
arr_1d = np.array([1,2,4])
print(arr_1d)

[1 2 4]


In [6]:
arr_2d = np.array([[1,2,3,4],[3,6,2,9]])
print(arr_2d)

[[1 2 3 4]
 [3 6 2 9]]


In [7]:
py_list = [1,2,3]
print("python list multiplication",py_list*2)

python list multiplication [1, 2, 3, 1, 2, 3]


In [8]:
np_array = np.array([1,2,3])
print("python array multiplication",np_array*2)

python array multiplication [2 4 6]


In [10]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("python list multiplication time" ,time.time()-start)

start = time.time()
np_array = np.arange(10000000)*2
print("Numpy array multiplication time" ,time.time()-start)

python list multiplication time 0.6285953521728516
Numpy array multiplication time 0.050821781158447266


In [12]:
zeroes = np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
full_array = np.full((3,4),6)
print(full_array)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [16]:
random_array = np.random.random((3,4))
print(random_array)

[[0.79771027 0.0574873  0.48300914 0.23712588]
 [0.93168529 0.59530117 0.99211789 0.28117842]
 [0.02329793 0.64986921 0.98451101 0.00711247]]


In [18]:
sequence = np.arange(2,42,3)
print(sequence)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41]


**Vector, Matrix, Tensor**

In [23]:
vector = np.array([1,2,3])
print("Vector is given below \n")
print(vector)

print("\n")

matrix = np.array([[1,3,4],[5,7,2]])
print("Matrix is given below \n")
print(matrix)

print("\n")

Tensor = np.array([[[1,4,3],[2,7,3]],[[2,4,7],[6,4,8]]])
print("Tensor is given below \n")
print(Tensor)

Vector is given below 

[1 2 3]


Matrix is given below 

[[1 3 4]
 [5 7 2]]


Tensor is given below 

[[[1 4 3]
  [2 7 3]]

 [[2 4 7]
  [6 4 8]]]


**Properties of Array**

In [48]:
arr1 = np.array([[1,2,9],[4,5,7]])
print(arr1)
print("\n")
print("Shape",arr1.shape)
print("Dimension",arr1.ndim)
print("Size",arr1.size)
print("Data type",arr1.dtype)

[[1 2 9]
 [4 5 7]]


Shape (2, 3)
Dimension 2
Size 6
Data type int64


In [46]:
arr = np.arange(12)
print("Original array \n",arr)

arr = arr.reshape(3,4)
print("Reshaped array \n",arr)

arr = arr.reshape(3,2,2)
print("Reshaped array \n",arr)

arr = arr.flatten() #flatten function hamesha array ki copy me change krta hai
print("Flattened array \n",arr)

print("\n")
arr = arr.ravel() #ravel function hamesha original array me change krta hai

print("raveled array",arr)

Original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Flattened array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
arr1 = np.array([[1,2,9],[4,5,7]])
arr = arr1.T
print(arr)

[[1 4]
 [2 5]
 [9 7]]
