<a href="https://colab.research.google.com/github/digvijay-sharma123/Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
arr_1d = np.array([1,2,4])
print(arr_1d)

[1 2 4]


In [6]:
arr_2d = np.array([[1,2,3,4],[3,6,2,9]])
print(arr_2d)

[[1 2 3 4]
 [3 6 2 9]]


In [7]:
py_list = [1,2,3]
print("python list multiplication",py_list*2)

python list multiplication [1, 2, 3, 1, 2, 3]


In [8]:
np_array = np.array([1,2,3])
print("python array multiplication",np_array*2)

python array multiplication [2 4 6]


In [10]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("python list multiplication time" ,time.time()-start)

start = time.time()
np_array = np.arange(10000000)*2
print("Numpy array multiplication time" ,time.time()-start)

python list multiplication time 0.6285953521728516
Numpy array multiplication time 0.050821781158447266


In [12]:
zeroes = np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
full_array = np.full((3,4),6)
print(full_array)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
