<a href="https://colab.research.google.com/github/digvijay-sharma123/Pandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,4])
print(arr_1d)

[1 2 4]


In [ ]:
arr_2d = np.array([[1,2,3,4],[3,6,2,9]])
print(arr_2d)

[[1 2 3 4]
 [3 6 2 9]]


In [ ]:
py_list = [1,2,3]
print("python list multiplication",py_list*2)

python list multiplication [1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1,2,3])
print("python array multiplication",np_array*2)

python array multiplication [2 4 6]


In [ ]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("python list multiplication time" ,time.time()-start)

start = time.time()
np_array = np.arange(10000000)*2
print("Numpy array multiplication time" ,time.time()-start)

python list multiplication time 0.6255683898925781
Numpy array multiplication time 0.04117417335510254


In [ ]:
zeroes = np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
full_array = np.full((3,4),6)
print(full_array)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
random_array = np.random.random((3,4))
print(random_array)

[[0.1044764  0.98523214 0.66545445 0.33393165]
 [0.41754147 0.28241037 0.2690333  0.06124831]
 [0.87776983 0.06178599 0.44151708 0.12864681]]


In [ ]:
sequence = np.arange(2,42,3)
print(sequence)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41]


**Vector, Matrix, Tensor**

In [ ]:
vector = np.array([1,2,3])
print("Vector is given below \n")
print(vector)

print("\n")

matrix = np.array([[1,3,4],[5,7,2]])
print("Matrix is given below \n")
print(matrix)

print("\n")

Tensor = np.array([[[1,4,3],[2,7,3]],[[2,4,7],[6,4,8]]])
print("Tensor is given below \n")
print(Tensor)

Vector is given below 

[1 2 3]


Matrix is given below 

[[1 3 4]
 [5 7 2]]


Tensor is given below 

[[[1 4 3]
  [2 7 3]]

 [[2 4 7]
  [6 4 8]]]


**Properties of Array**

In [ ]:
arr1 = np.array([[1,2,9],[4,5,7]])
print(arr1)
print("\n")
print("Shape",arr1.shape)
print("Dimension",arr1.ndim)
print("Size",arr1.size)
print("Data type",arr1.dtype)

[[1 2 9]
 [4 5 7]]


Shape (2, 3)
Dimension 2
Size 6
Data type int64


In [ ]:
arr = np.arange(12)
print("Original array \n",arr)

arr = arr.reshape(3,4)
print("Reshaped array \n",arr)

arr = arr.reshape(3,2,2)
print("Reshaped array \n",arr)

arr = arr.flatten() #flatten function hamesha array ki copy me change krta hai
print("Flattened array \n",arr)

print("\n")
arr = arr.ravel() #ravel function hamesha original array me change krta hai

print("raveled array",arr)

Original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Flattened array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr1 = np.array([[1,2,9],[4,5,7]])
arr = arr1.T
print(arr)

[[1 4]
 [2 5]
 [9 7]]


**Phase-2**

In [ ]:
arr = np.array([[1,2,9],[4,5,7]])
arr = arr.flatten()
print("Original Array",arr)
print("Sorted Array", np.sort(arr))

Original Array [1 2 9 4 5 7]
Sorted Array [1 2 4 5 7 9]


In [ ]:
arr = np.array([[1,6,9],[4,5,7]])
print("Original Array \n",arr)
print("Sorted Array \n", np.sort(arr,axis=0))  ## axis=0 column sorting hota

Original Array 
 [[1 6 9]
 [4 5 7]]
Sorted Array 
 [[1 5 7]
 [4 6 9]]


In [27]:
arr = np.array([[1,2,9],[4,5,7]])
arr = arr.flatten()
even_numbers = arr[arr%2==0]
print("Even numbers",even_numbers)

Even numbers [2 4]


In [28]:
mask = arr>2
print("Number greater than 2 ", arr[mask])

Number greater than 2  [9 4 5 7]


In [29]:
index = [0,1,3]
print("Original array", arr[index])

where_result = np.where(arr>2)
print("where_result",arr[where_result])

Original array [1 2 4]
where_result [9 4 5 7]


In [35]:
arr = np.array([[1,2,9],[4,8,7]])
arr1 = np.array([[1,3,4],[4,5,7]])

combined = arr+arr1
print("Combined array \n",combined) # shape should be same for both array
concat_array = np.concatenate((arr,arr1),axis=0)
print("arr \n",arr)
print("arr1 \n",arr1)
print("Concatenated array \n",concat_array)

Combined array 
 [[ 2  5 13]
 [ 8 13 14]]
arr 
 [[1 2 9]
 [4 8 7]]
arr1 
 [[1 3 4]
 [4 5 7]]
Concatenated array 
 [[1 2 9]
 [4 8 7]
 [1 3 4]
 [4 5 7]]


In [37]:
arr= np.array([[1,2,3],[2,3,5]])
new_row = np.array([[5,7,2]])
new_arr = np.vstack((arr,new_row))
print("New array \n",new_arr)
new_col = np.array([[2,3,4],[3,6,7]])
new_arr = np.hstack((arr,new_col))
print("New array \n",new_arr)

New array 
 [[1 2 3]
 [2 3 5]
 [5 7 2]]
New array 
 [[1 2 3 2 3 4]
 [2 3 5 3 6 7]]


In [40]:
deleted = np.delete(arr,[1,2]) ## simply pass arr and index of element that should be deleted
print(deleted)

[1 2 3 5]


**Phase-3**